---
name: Release
on:
  push:
    branches:
      - main

jobs:
  release-automation:
    # Pin to the latest version to avoid circular dependency
    uses: juancarlosjr97/github-actions-workflows-to-rule-them-all/.github/workflows/shared-release-automation.yml@7610c3e9832c0eb632cdbf1a6026bac4d5c4c8d0 # main
    secrets:
      PROJECT_GITHUB_TOKEN: ${{ secrets.PROJECT_GITHUB_TOKEN }}
    with:
      PLUGIN_LIST: "@release-it/conventional-changelog,@release-it/bumper"
